/* eslint-disable react-hooks/exhaustive-deps, @next/next/no-img-element */
"use client";
import {useEffect,useState} from "react";
type Player={id:number;name:string;grade:string;team:string;subject?:string;score:number;correct:number};
type Team={team:string;totalScore:number;totalCorrect?:number;players:number};
type LiveState={name?:string;status?:string;players?:number};
const modes=[{value:"all",label:"Geral"},{value:"math",label:"Matemática"},{value:"portuguese",label:"Português"},{value:"mixed",label:"Aleatório"}];
const statusLabel:Record<string,string>={waiting:"Sala aberta",running:"Disputa ao vivo",paused:"Competição pausada",finished:"Rodada encerrada",open:"Jogo livre"};
const medals=["🥇","🥈","🥉"];
export default function Projector(){
 const [live,setLive]=useState<LiveState>({}),[players,setPlayers]=useState<Player[]>([]),[teams,setTeams]=useState<Team[]>([]),[mode,setMode]=useState("all"),[updated,setUpdated]=useState<Date|null>(null),[loading,setLoading]=useState(true);
 async function load(selected=mode){try{const [room,ranking]=await Promise.all([fetch("/api/live").then(response=>response.json()),fetch(`/api/ranking?period=round&subject=${selected}`).then(response=>response.json())]);setLive(room);setPlayers(ranking.scores||[]);setTeams(ranking.teams||[]);setUpdated(new Date())}finally{setLoading(false)}}
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),5000);return()=>clearInterval(timer)},[mode]);
 function changeMode(value:string){setMode(value);setLoading(true);void load(value)}
 function fullscreen(){if(!document.fullscreenElement)void document.documentElement.requestFullscreen();else void document.exitFullscreen()}
 const podium=[players[1],players[0],players[2]],totalPoints=teams.reduce((sum,item)=>sum+Number(item.totalScore||0),0),status=live.status||"open";
 return <main className="projector projector-v2"><div className="projector-glow one"/><div className="projector-glow two"/>
  <header><div className="projector-brand"><img src="/logo-erem-clovis-bevilaqua.png" alt="Logo da EREM Clóvis Beviláqua"/><div><small>EREM CLÓVIS BEVILÁQUA</small><h1>{live.name||"Arena do Conhecimento"}</h1><p>Conhecimento que une. Equipes que fazem história.</p></div></div><div className="projector-live"><span className={`live-pill ${status}`}><i/>{statusLabel[status]||"Preparando"}</span><button onClick={fullscreen} title="Tela cheia">⛶</button></div></header>
  <nav className="projector-modes">{modes.map(item=><button key={item.value} className={mode===item.value?"active":""} onClick={()=>changeMode(item.value)}>{item.label}</button>)}</nav>
  <section className="projector-summary"><article><small>PARTICIPANTES</small><strong>{live.players||players.length}</strong><span>na rodada atual</span></article><article><small>MAIOR PONTUAÇÃO</small><strong>{players[0]?.score?.toLocaleString("pt-BR")||0}</strong><span>{players[0]?.name||"Aguardando resultados"}</span></article><article><small>PONTOS DAS EQUIPES</small><strong>{totalPoints.toLocaleString("pt-BR")}</strong><span>{teams.length} delegações no ranking</span></article><article><small>ATUALIZAÇÃO</small><strong className="projector-clock">{updated?.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})||"--:--"}</strong><span>automática a cada 5 segundos</span></article></section>
  {loading?<section className="projector-wait"><i/><p>Atualizando o placar…</p></section>:players.length===0?<section className="projector-empty"><b>🏁</b><h2>A arena está pronta</h2><p>Os resultados aparecerão aqui assim que os estudantes concluírem a primeira partida.</p></section>:<>
  <section className="projector-podium"><div className="projector-section-title"><div><small>DESTAQUES DA RODADA</small><h2>Pódio dos jogadores</h2></div><span>TOP 3</span></div><div className="podium-stage">{podium.map((player,index)=>player&&<article className={`podium-card place-${index===0?2:index===1?1:3}`} key={player.id}><span>{medals[index===0?1:index===1?0:2]}</span><div className="podium-avatar">{player.name.slice(0,1).toUpperCase()}</div><strong>{player.name}</strong><small>{player.grade} • {player.team}</small><b>{player.score.toLocaleString("pt-BR")} pts</b><em>{player.correct}/10 acertos</em></article>)}</div></section>
  <div className="projector-grid"><section><div className="projector-section-title"><div><small>CLASSIFICAÇÃO</small><h2>Jogadores</h2></div><span>TOP 10</span></div>{players.slice(0,10).map((player,index)=><article className="projector-row" key={player.id}><b className={`rank-${index+1}`}>{index+1}</b><div><strong>{player.name}</strong><span>{player.grade} • {player.team}</span></div><em>{player.score.toLocaleString("pt-BR")}</em></article>)}</section><section><div className="projector-section-title"><div><small>DISPUTA COLETIVA</small><h2>Delegações</h2></div><span>POR EQUIPE</span></div>{teams.slice(0,10).map((team,index)=><article className="projector-row team-row" key={team.team}><b className={`rank-${index+1}`}>{index+1}</b><div><strong>{team.team}</strong><span>{team.players} participações • {Number(team.totalCorrect||0)} acertos</span></div><em>{Number(team.totalScore).toLocaleString("pt-BR")}</em></article>)}</section></div></>}
  <footer><span>ARENA DO CONHECIMENTO • 2026</span><i>{mode==="all"?"Classificação geral":modes.find(item=>item.value===mode)?.label}</i></footer>
 </main>
}
