/* eslint-disable react-hooks/set-state-in-effect, @next/next/no-html-link-for-pages, @next/next/no-img-element */
"use client";
import {useEffect,useMemo,useState} from "react";
type Score={id:number;name:string;studentId:string;grade:string;team:string;subject?:"math"|"portuguese"|"mixed";correct:number;score:number;integrityStatus?:string;integrityNotes?:string};
type Stat={label:string;players?:number;attempts?:number;accuracy:number};type Topic={topic:string;total:number;correct:number;accuracy:number};type Dashboard={scores:Score[];topicStats:Topic[];gradeStats:Stat[];teamStats:Stat[]};
const SUBJECTS=[{value:"",label:"Todas",icon:"✦"},{value:"math",label:"Matemática",icon:"∑"},{value:"portuguese",label:"Português",icon:"文"},{value:"mixed",label:"Aleatório",icon:"◈"}];
const subjectLabel=(value?:string)=>SUBJECTS.find(item=>item.value===value)?.label||"Matemática";
export default function AdminPage(){
 const [auth,setAuth]=useState<boolean|null>(null),[data,setData]=useState<Dashboard>({scores:[],topicStats:[],gradeStats:[],teamStats:[]}),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[loginBusy,setLoginBusy]=useState(false);
 const [live,setLive]=useState("open"),[query,setQuery]=useState(""),[grade,setGrade]=useState(""),[team,setTeam]=useState(""),[subject,setSubject]=useState(""),[sort,setSort]=useState("score"),[busy,setBusy]=useState(false);
 const [roundName,setRoundName]=useState("Jogos Internos 2026"),[code,setCode]=useState("ARENA2026"),[studentsText,setStudentsText]=useState("");
 async function load(){setLoading(true);try{const admin=await fetch("/api/admin").then(r=>r.json());setAuth(Boolean(admin.isAdmin));if(!admin.isAdmin)return;const [dashboard,room]=await Promise.all([fetch("/api/admin/dashboard").then(r=>r.json()),fetch("/api/live").then(r=>r.json())]);setData({scores:dashboard.scores||[],topicStats:dashboard.topicStats||[],gradeStats:dashboard.gradeStats||[],teamStats:dashboard.teamStats||[]});setLive(room.status||"open")}catch{setMessage("Não foi possível carregar o painel.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const rows=useMemo(()=>data.scores.filter(item=>(!grade||item.grade===grade)&&(!team||item.team===team)&&(!subject||item.subject===subject)&&(!query||`${item.name} ${item.studentId}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):sort==="correct"?b.correct-a.correct:b.score-a.score),[data.scores,grade,team,subject,query,sort]);
 const students=new Set(rows.map(item=>item.studentId||`${item.name}|${item.grade}`)).size,average=rows.length?Math.round(rows.reduce((sum,item)=>sum+item.correct,0)/rows.length*10):0,totalPoints=rows.reduce((sum,item)=>sum+item.score,0),reviews=rows.filter(item=>item.integrityStatus==="review").length;
 const grades=[...new Set(data.scores.map(item=>item.grade))].sort(),teams=[...new Set(data.scores.map(item=>item.team))].sort();
 async function updateRoom(status:string){setLive(status);const response=await fetch("/api/admin/live",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(!response.ok)setMessage("Não foi possível atualizar a sala.")}
 async function createRound(){setBusy(true);const response=await fetch("/api/admin/competitions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:roundName,code,maxAttempts:1,scoringRule:"best"})});const result=await response.json();setMessage(response.ok?"Competição criada e ativada com sucesso.":result.error||"Não foi possível criar a competição.");if(response.ok)await load();setBusy(false)}
 async function importStudents(){const students=studentsText.trim().split(/\n/).map(line=>{const [studentId,name,grade,team,extraTime]=line.split(/[;,\t]/).map(value=>value.trim());return{studentId,name,grade,team,extraTime:/sim|true|1/i.test(extraTime||"")}}).filter(item=>item.studentId&&item.name&&item.grade&&item.team);if(!students.length){setMessage("Informe alunos no formato indicado.");return}setBusy(true);const response=await fetch("/api/admin/students",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({students})});const result=await response.json();setMessage(response.ok?`${result.count||students.length} alunos importados.`:result.error||"Falha na importação.");if(response.ok)setStudentsText("");setBusy(false)}
 async function clearHistory(){if(!confirm("Excluir definitivamente todo o histórico do ranking?"))return;setBusy(true);const response=await fetch("/api/ranking",{method:"DELETE"});setMessage(response.ok?"Histórico excluído.":"Não foi possível excluir o histórico.");await load();setBusy(false)}
 async function login(event:React.FormEvent){event.preventDefault();setLoginBusy(true);setMessage("");try{const response=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const result=await response.json();if(response.ok)await load();else setMessage(result.error||"Não foi possível entrar.")}catch{setMessage("O servidor não respondeu. Revise a configuração do Supabase.")}finally{setLoginBusy(false)}}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});setAuth(false);setData({scores:[],topicStats:[],gradeStats:[],teamStats:[]})}
 if(auth===null||loading)return <main className="admin-loading"><span/><p>Preparando a central de gestão…</p></main>;
 if(!auth)return <main className="admin-shell admin-access"><section className="admin-locked admin-locked-v2"><div className="access-logo"><img src="/logo-erem-clovis-bevilaqua.png" alt="Logo da escola"/><i>◆</i></div><p className="eyebrow">ÁREA RESTRITA</p><h1>Central da Arena</h1><p>Entre com a conta administrativa cadastrada. Os resultados e os dados dos estudantes permanecem protegidos.</p><form className="admin-login-form" onSubmit={login}><label><span>E-mail administrativo</span><input type="email" autoComplete="username" value={email} onChange={event=>setEmail(event.target.value)} placeholder="seuemail@escola.com" required/></label><label><span>Senha</span><input type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)} placeholder="Digite sua senha" required/></label>{message&&<p className="login-error">{message}</p>}<button disabled={loginBusy}>{loginBusy?"Entrando…":"Entrar no painel"}</button></form><div className="access-security"><span>✓ Dados protegidos</span><span>✓ Sessão segura</span></div><a href="/">← Voltar ao jogo</a><small>EREM CLÓVIS BEVILÁQUA • GESTÃO 2026</small></section></main>;
 return <main className="admin-shell admin-v2"><aside className="admin-sidebar"><div className="admin-brand"><img src="/logo-erem-clovis-bevilaqua.png" alt="Logo da escola"/><span><b>Arena</b><small>Conhecimento</small></span></div><nav><a className="active" href="#visao">⌂ <span>Visão geral</span></a><a href="#competicao">● <span>Competição</span></a><a href="#pedagogico">◫ <span>Pedagógico</span></a><a href="#resultados">▤ <span>Resultados</span></a><a href="#alunos">♙ <span>Alunos</span></a></nav><div className="sidebar-actions"><a href="/projector" target="_blank">▣ Abrir telão</a><a href="/">← Voltar ao jogo</a></div></aside><div className="admin-content">
 <header id="visao" className="admin-top"><div><p>EREM CLÓVIS BEVILÁQUA</p><h1>Central da Arena</h1><span>Acompanhamento pedagógico e gestão da competição</span></div><div className="admin-buttons"><button onClick={()=>void load()}>↻ Atualizar</button><a href="/projector" target="_blank">Abrir telão</a><button onClick={()=>void logout()}>Sair</button></div></header>
 {message&&<div className="admin-notice"><span>{message}</span><button onClick={()=>setMessage("")}>×</button></div>}
 <nav className="admin-subject-filter">{SUBJECTS.map(item=><button key={item.value} className={subject===item.value?"active":""} onClick={()=>setSubject(item.value)}><i>{item.icon}</i>{item.label}</button>)}</nav>
 <section className="admin-kpis"><article><small>ALUNOS</small><strong>{students}</strong><span>participantes únicos</span></article><article><small>TENTATIVAS</small><strong>{rows.length}</strong><span>resultados filtrados</span></article><article><small>APROVEITAMENTO</small><strong>{average}%</strong><span>média de acertos</span></article><article><small>PONTOS</small><strong>{totalPoints.toLocaleString("pt-BR")}</strong><span>{reviews} para revisar</span></article></section>
 <section id="competicao" className="admin-card admin-control"><div className="admin-card-title"><div><small>CONTROLE AO VIVO</small><h2>Estado da competição</h2></div><span className={`room-status ${live}`}>● {live}</span></div><div className="live-controls">{[["waiting","Abrir sala"],["running","Iniciar disputa"],["paused","Pausar"],["finished","Encerrar"]].map(([value,label])=><button className={live===value?"active":""} key={value} onClick={()=>void updateRoom(value)}>{label}</button>)}</div></section>
 <div className="admin-grid"><section className="admin-card"><div className="admin-card-title"><div><small>NOVA RODADA</small><h2>Criar competição</h2></div></div><div className="round-form"><label>Nome<input value={roundName} onChange={event=>setRoundName(event.target.value)}/></label><label>Código<input value={code} onChange={event=>setCode(event.target.value.toUpperCase())}/></label><button disabled={busy||!roundName.trim()||!code.trim()} onClick={()=>void createRound()}>{busy?"Aguarde…":"Criar e ativar"}</button></div></section><section className="admin-card admin-summary"><div className="admin-card-title"><div><small>RESUMO</small><h2>Leitura rápida</h2></div></div><p><b>{rows[0]?.name||"Nenhum aluno"}</b><span>liderança atual</span></p><p><b>{rows[0]?.score?.toLocaleString("pt-BR")||0}</b><span>maior pontuação</span></p><p><b>{subjectLabel(subject)}</b><span>modalidade exibida</span></p></section></div>
 <div id="pedagogico" className="admin-grid"><section className="admin-card gaps"><div className="admin-card-title"><div><small>DIAGNÓSTICO</small><h2>Conteúdos para reforçar</h2></div></div>{data.topicStats.length?data.topicStats.slice(0,10).map(item=><div className="topic-row" key={item.topic}><div><strong>{item.topic}</strong><span>{item.correct} de {item.total} corretas</span></div><em>{item.accuracy}%</em><i><b style={{width:`${item.accuracy}%`}}/></i></div>):<p className="admin-empty">Os dados aparecerão após as primeiras partidas.</p>}</section><section className="admin-card"><div className="admin-card-title"><div><small>COMPARATIVO</small><h2>Turmas e equipes</h2></div></div>{[...data.gradeStats,...data.teamStats].slice(0,14).map(item=><div className="stat-row" key={item.label}><strong>{item.label}</strong><span>{item.players||item.attempts||0} participações</span><b>{item.accuracy}%</b></div>)}</section></div>
 <section id="resultados" className="admin-card results-card"><div className="admin-card-title"><div><small>BANCO DE RESULTADOS</small><h2>Resultados</h2></div><div className="admin-buttons"><a href="/api/export">↓ Baixar CSV</a><button className="danger" disabled={busy||!data.scores.length} onClick={()=>void clearHistory()}>Excluir histórico</button></div></div><div className="admin-filters"><input placeholder="Buscar nome ou matrícula" value={query} onChange={event=>setQuery(event.target.value)}/><select value={grade} onChange={event=>setGrade(event.target.value)}><option value="">Todas as turmas</option>{grades.map(value=><option key={value}>{value}</option>)}</select><select value={team} onChange={event=>setTeam(event.target.value)}><option value="">Todos os times</option>{teams.map(value=><option key={value}>{value}</option>)}</select><select value={sort} onChange={event=>setSort(event.target.value)}><option value="score">Maior pontuação</option><option value="correct">Mais acertos</option><option value="name">Nome A–Z</option></select></div><div className="admin-table-wrap"><table><thead><tr><th>#</th><th>Aluno</th><th>Turma / time</th><th>Modalidade</th><th>Acertos</th><th>Pontos</th><th>Status</th></tr></thead><tbody>{rows.slice(0,500).map((item,index)=><tr key={item.id}><td>{index+1}</td><td><strong>{item.name}</strong><small>{item.studentId||"Sem matrícula"}</small></td><td>{item.grade}<small>{item.team}</small></td><td><span className={`subject-chip ${item.subject||"math"}`}>{subjectLabel(item.subject)}</span></td><td>{item.correct}/10</td><td><strong>{item.score.toLocaleString("pt-BR")}</strong></td><td title={item.integrityNotes}><span className={item.integrityStatus==="review"?"status-review":"status-ok"}>{item.integrityStatus==="review"?"Revisar":"Validado"}</span></td></tr>)}</tbody></table>{!rows.length&&<p className="admin-empty">Nenhum resultado encontrado.</p>}</div></section>
 <section id="alunos" className="admin-card import-card"><div className="admin-card-title"><div><small>CADASTRO EM LOTE</small><h2>Importar estudantes</h2></div><span>matrícula; nome; turma; time; tempo adaptado</span></div><textarea value={studentsText} onChange={event=>setStudentsText(event.target.value)} placeholder="2026001; Ana Silva; 1º ano A; Austrália; não\n2026002; João Santos; 2º ano B; Espanha; sim"/><div><small>Uma linha por estudante.</small><button disabled={busy||!studentsText.trim()} onClick={()=>void importStudents()}>{busy?"Processando…":"Importar alunos"}</button></div></section>
 </div></main>
}
